package roth.lib.java.service;

public enum HttpErrorType
{
	HTTP_ORIGIN_UNSUPPORTED,
	HTTP_METHOD_MISSING,
	HTTP_METHOD_NOT_SUPPORTED,
	HTTP_METHOD_NOT_IMPLEMENTED,
	SERVICE_METHOD_NAME_MISSING,
	SERVICE_NOT_IMPLEMENTED,
	SERVICE_METHOD_MISSING,
	SERVICE_METHOD_PARAMETER_INVALID,
	SERVICE_AJAX_NOT_AUTHENTICATED,
	SERVICE_API_NOT_AUTHENTICATED,
	SERVICE_CHANNEL_NOT_IMPLEMENTED,
	SERVICE_CSRF_TOKEN_INVALID,
	SERVICE_NOT_AUTHORIZED,
	SERVICE_EXCEPTION,
	REQUEST_FIELD_REQUIRED,
	REQUEST_FIELD_INVALID,
	DATABASE_CONNECTION_EXCEPTION,
	;
	
	public HttpError error()
	{
		return new HttpError(this);
	}
	
	public HttpError error(Throwable e)
	{
		return new HttpError(this).setMessage(e.getMessage());
	}
	
}
